import './globals.css'
import { ReactNode } from 'react'
import Link from "next/link";

export const metadata = {
    title: 'WEB tutorial',
    description: 'Generated by HJ',
}

interface Props {
    children: ReactNode
}

export default function RootLayout(props : Props) {
    return (
        <html>
        <body>
        <h1><a href="/">WEB</a></h1>
        <ol>
            <li><Link href="/read/1">html</Link></li>
            <li><Link href="/read/2">css</Link></li>
        </ol>
        {props.children}
        <ul>
            <li><Link href="/pages/create">create</Link></li>
            <li><Link href="/update/id">update</Link></li>
            <li><button>delete</button></li>
        </ul>
        </body>
        </html>
    )
}