import './globals.css'
import { ReactNode } from 'react'
import Link from "next/link";
import {Control} from "./Control";

export const metadata = {
    title: 'WEB tutorial',
    description: 'Generated by HJ',
    icons: {
        icon: "/hello.png",
    }
}

interface Props {
    children: ReactNode
}

export default async function RootLayout(props: Props) {
    // server component에서는 fetch를 사용할 때 useEffect를 사용하지 않음
    // 또 fetch를 이용할 때 await를 사용
    // {cache:'no-cache'}를 추가하면 캐쉬를 사용하지 않게 됨
    // 이제 layout.js의 fetch는 랜더링 될 때마다 캐쉬를 사용하지 않고 신선한 데이터를 가져옴
    const resp = await fetch(`${process.env.NEXT_PUBLIC_API_URL}/topics/`, {cache:'no-cache'})
    const topics = await resp.json();

    return (
        <html>
        <body>
        <h1><a href="/">WEB</a></h1>
        <ol>
            {/* 글 목록 생성 */}
            {topics.map(topic => {
                return <li key={topic.id}><Link href={`/read/${topic.id}`}>{topic.title}</Link></li>
            })}
        </ol>
        {props.children}
        <Control />
        </body>
        </html>
    )
}